---
title: "Compute systems at the BioCommons partner infrastructures"
---

Below is a list of the Australian BioCommons infrastructure partners and some of their available compute systems. This list is not intended to be exhaustive, and will grow as the BioCommons develops.

-----

-----

# FAQ: can I get a HPC allocation through the BioCommons?

Allocation of computational resources to individual researchers on partner HPC and cloud infrastructures is through the usual channels offered via each partner (see instructions for each by following these links: [NCI](https://nci.org.au/users/how-access-nci), [Pawsey](https://support.pawsey.org.au/documentation/display/US/Getting+Access), [QCIF](https://www.qcif.edu.au/services/computing/), [ARDC-Nectar](http://cloud.nectar.org.au/start-now/)). The [BioCommons BioCloud](https://www.biocommons.org.au/biocloud) activity is working with these partners to examine ways to make it easier for life science researchers to receive HPC and HTC allocations.

Note that access to computational resources via the [Galaxy Australia](https://usegalaxy.org.au/) hosted web platform is unlimited for Australian researchers thanks to our computational partners (ARDC-Nectar Cloud, University of Queensland, QCIF, University of Melbourne and Pawsey) who underpin the Galaxy Australia service.  

-----

-----

# Graphical user interface accessible systems

- [**Galaxy Australia**](https://usegalaxy.org.au/)
- [**SWAN** (Rstudio & JupyterLab accessible via AARNet’s CloudStor)](https://support.aarnet.edu.au/hc/en-us/sections/360000129695-CloudStor-SWAN)

-----

-----

# Command-line accessible systems

## Partner High Performance Computing (HPC) systems

- [**National Computational Infrastructure (NCI)**](https://nci.org.au/)
    - [Gadi](https://opus.nci.org.au/display/Help/Gadi+User+Guide)
- [**Pawsey Supercomputing Centre**](https://pawsey.org.au/)
    - [Magnus](https://pawsey.org.au/systems/magnus/)
    - [Zeus](https://pawsey.org.au/systems/zeus/)
    - [Topaz](https://pawsey.org.au/systems/topaz/)
- [**Queensland Cyber Infrastructure Foundation (QCIF) / University of Queensland - Research Computing Centre (RCC)**](https://rcc.uq.edu.au/)
    - [Flashlite](https://rcc.uq.edu.au/flashlite)
    - [Tinaroo](https://rcc.uq.edu.au/tinaroo)
    - [Awoonga](https://rcc.uq.edu.au/awoonga)
- [**University of Sydney**](https://www.sydney.edu.au/)
    - [Artemis](https://www.sydney.edu.au/research/facilities/sydney-informatics-hub/digital-research-infrastructure.html)
- [**University of Melbourne**](https://www.unimelb.edu.au/)
    - [Spartan](https://dashboard.hpc.unimelb.edu.au/)

## Partner Cloud compute systems

- [**Pawsey Supercomputing Centre**](https://pawsey.org.au/)
    - [Nimbus research cloud](https://pawsey.org.au/systems/nimbus-cloud-service/)
- [**Queensland Cyber Infrastructure Foundation (QCIF) / University of Queensland - Research Computing Centre (RCC)**](https://rcc.uq.edu.au/)
    - [QRISCloud](https://rcc.uq.edu.au/qriscloud)
- [**Australian Research Data Commons (ARDC)**](https://ardc.edu.au/)
    - [Nectar Research cloud](https://ardc.edu.au/services/nectar-research-cloud/)

-----

-----

```{r echo = FALSE, message = FALSE}
#see https://bookdown.org/yihui/rmarkdown-cookbook/write-bib.html
library(knitr)
write_bib(c(.packages()), "./outputs/compute_systems_packages.bib")
```
