---
title: "Attributions"
bibliography: ./outputs/bib_all.bib
nocite: '@*'
---

# General references 

### Tool metadata was sourced from [bio.tools](https://bio.tools/) where possible

- Ison, J. et al. (2015). Tools and data services registry: a community effort to document bioinformatics resources. Nucleic Acids Research. [DOI](https://doi.org/10.1093/nar/gkv1116)
- [bio.tools API](https://biotools.readthedocs.io/en/latest/api_reference.html)

### EDAM was used for tool list categorisation

- Ison, J., Kalaš, M., Jonassen, I., Bolser, D., Uludag, M., McWilliam, H., Malone, J., Lopez, R., Pettifer, S. and Rice, P. 2013. EDAM: an ontology of bioinformatics operations, types of data and identifiers, topics and formats. Bioinformatics, 29(10): 1325-1332. [DOI](https://doi.org/10.1093/bioinformatics/btt113) PMID: 23479348 *Open Access*
- [EDAM ontology GitHub](https://github.com/edamontology/edamontology)

### For site construction

- Rmarkdown
     - [Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/)
     - [Site](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html)
     - [Appearance & style](https://bookdown.org/yihui/rmarkdown/html-document.html#appearance-and-style)
     - [Rstudio lesson for rmarkdown: lesson 13](https://rmarkdown.rstudio.com/lesson-13.html)
     - [New tab for links](https://community.rstudio.com/t/how-to-direct-a-link-to-another-tab-in-md-files/48737/2)
     - [Site navigation](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html#site-navigation)
     - [Code folding](https://bookdown.org/yihui/rmarkdown-cookbook/fold-show.html)
     - [Interactive documents](https://bookdown.org/yihui/rmarkdown/interactive-documents.html)
     - [Favicon](https://bookdown.org/yihui/rmarkdown-cookbook/favicon.html)
     - [Write .bib](https://bookdown.org/yihui/rmarkdown-cookbook/write-bib.html)
- [New tab for links: HTML](https://stackoverflow.com/a/17711167)
- [GitHub & Rstudio whitepaper](https://resources.github.com/whitepapers/github-and-rstudio/)
- [HTML anchors](https://stackoverflow.com/a/7015050)
- [DT](https://rstudio.github.io/DT/)
- [DT extensions (e.g. buttons)](https://rstudio.github.io/DT/extensions.html)
- [Image hyperlinks](https://stackoverflow.com/a/42235353)
- [Google Analytics](https://stackoverflow.com/a/45169407)
- CSS attributions
     - [Add footer](https://bookdown.org/yihui/rmarkdown-cookbook/include-html.html)
     - [Footer general structure](https://github.com/rstudio/rmarkdown/issues/1761#issuecomment-574875775)
     - [CSS colors](https://www.w3schools.com/cssref/css_colors.asp)
     - [CSS footer color](https://stackoverflow.com/a/38387051)
     - [CSS text align](https://www.w3schools.com/cssref/pr_text_text-align.ASP)
     - [CSS fonts](https://stackoverflow.com/a/29298407)
     - [CSS navbar format](https://stackoverflow.com/a/62798548)
     - [CSS page width](https://stackoverflow.com/a/46564977)
     - [CSS website layout](https://www.w3schools.com/css/css_website_layout.asp)
- [HTML-tabsets](https://bookdown.org/yihui/rmarkdown-cookbook/html-tabs.html)
- [HTML-text sizing](https://stackoverflow.com/a/44906182)
- [httr](https://cran.r-project.org/web/packages/httr/vignettes/quickstart.html)
- [tryCatch](https://stackoverflow.com/questions/12193779/how-to-write-trycatch-in-r)
- [tidyjson](https://cran.r-project.org/web/packages/tidyjson/vignettes/introduction-to-tidyjson.html)
- [uuid](https://cran.r-project.org/web/packages/uuid/uuid.pdf)


Xie Yihui, Dervieux Christophe, Riederer Emily. 2020. R Markdown Cookbook. [https://bookdown.org/yihui/rmarkdown-cookbook/](https://bookdown.org/yihui/rmarkdown-cookbook/)

Xie Yihui, Allaire J. J., Grolemund Garrett. 2020. R Markdown: The Definitive Guide. [https://bookdown.org/yihui/rmarkdown/](https://bookdown.org/yihui/rmarkdown/)

R Core Team (2020). R: A language and environment for statistical computing. R Foundation for Statistical Computing,
  Vienna, Austria. URL https://www.R-project.org/.

-----

-----

# Package citations

```{r echo = FALSE, message = FALSE}
#see https://cran.r-project.org/web/packages/RefManageR/RefManageR.pdf
library(RefManageR)
biocommons <- ReadBib("./outputs/biocommons_packages.bib")
compute <- ReadBib("./outputs/compute_systems_packages.bib")
help <- ReadBib("./outputs/help_packages.bib")
index <- ReadBib("./outputs/index_packages.bib")
tools <- ReadBib("./outputs/tools_packages.bib")

bib_all <- tools + index + biocommons + compute + help
WriteBib(bib_all, "./outputs/bib_all.bib")
```

